name: Deploy to Targetboard Web Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass openssh-client

      - name: Run remote build commands via SSH
        run: bash devops/scripts/deploy.sh

      - name: Run remote start commands via SSH
        run: bash devops/scripts/start.sh

