name: Deploy to Targetboard Web Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies and build
        run: |
          echo "[+] Installing dependencies..."
          npm install

          echo "[+] Building the project..."
          npm run build
        shell: bash

      - name: Install rsync and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass rsync openssh-client
        shell: bash

      - name: Rsync files to targetboard
        run: bash devops/scripts/build.sh
        shell: bash

      - name: Restart PM2 process remotely
        run: bash devops/scripts/start.sh
        shell: bash

